[package]
name = "imperium"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bumpalo = { version = "3.20", features = ["collections"] }
macroquad = "0.4"
num_enum = "0.7"
strum = { version = "0.28", features = ["derive"] }

arena = { path = "crates/arena" }
tabula = { path = "crates/tabula" }

[dependencies]
arena = { workspace = true }
macroquad = { workspace = true }
num_enum = { workspace = true }
tabula = { workspace = true }
strum = { workspace = true }
