[package]
name = "imperium"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bumpalo = { version = "*", features = ["collections"] }
strum = { version = "*", features = ["derive"] }

arena = { path = "crates/arena" }
tabula = { path = "crates/tabula" }

[dependencies]
arena = { workspace = true }
bumpalo = { workspace = true }
tabula = { workspace = true }
strum = { workspace = true}


