[package]
name = "imperium"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
bumpalo = { version = "3.20", features = ["collections"] }
macroquad = "0.4"
num_enum = "0.7"
strum = { version = "0.28", features = ["derive"] }

arena = { path = "crates/arena" }
entities = { path = "crates/entities" }
game = { path = "crates/game" }
tabula = { path = "crates/tabula" }
ui = { path = "crates/ui" }
util = { path = "crates/util" }

[dependencies]
arena = { workspace = true }
game = { workspace = true }
macroquad = { workspace = true }
ui = { workspace = true }
